version: '3.4'

services:
  hungrydays.blazor:
    image: ${DOCKER_REGISTRY-}hungrydays.blazor
    build:
      context: ..
      dockerfile: ./HungryDays.Blazor/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6071:80"
    depends_on:
    - hungrydays.database
  
  hungrydays.database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "@Development1"
        ACCEPT_EULA: "Y"
    ports:
    - 1433:1433