version: '3.4'

services:
  hungrydays.api:
    image: ${DOCKER_REGISTRY-}hungrydays.api
    build:
      context: ..
      dockerfile: HungryDays.Api/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6072:80"
    depends_on:
    - hungrydays.database
  
  hungrydays.database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "@Development1"
        ACCEPT_EULA: "Y"
    ports:
    - 1433:1433


  hungrydays.angular:
    image: ${DOCKER_REGISTRY-}hungrydays.angular
    build:
     context: ..
     dockerfile: HungryDays.Angular/Dockerfile
    ports:
     - "6073:80" 


