// <auto-generated />
using System;
using HungryDays.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HungryDays.Database.Migrations
{
    [DbContext(typeof(HungryDaysDbContext))]
    [Migration("20220804193633_OneToManyRelationship")]
    partial class OneToManyRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HungryDays.Database.Entities.HungryDayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HungryDays");
                });

            modelBuilder.Entity("HungryDays.Database.Entities.HungryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bought")
                        .HasColumnType("bit");

                    b.Property<int>("HungryDayID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HungryDayID");

                    b.ToTable("HungryItems");
                });

            modelBuilder.Entity("HungryDays.Database.Entities.HungryItemEntity", b =>
                {
                    b.HasOne("HungryDays.Database.Entities.HungryDayEntity", "HungryDay")
                        .WithMany("HungryItems")
                        .HasForeignKey("HungryDayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HungryDay");
                });

            modelBuilder.Entity("HungryDays.Database.Entities.HungryDayEntity", b =>
                {
                    b.Navigation("HungryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
